#!/bin/sh
set -e
# Automatically added by dh_installmodules/13.14.1
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -e /boot/System.map-5.4-147-samsung-a52sxq ]; then
		depmod -a -F /boot/System.map-5.4-147-samsung-a52sxq 5.4-147-samsung-a52sxq || true
	fi
fi
# End automatically added section
